/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.gestioncinema2.forms;

import com.example.gestioncinema2.Classes.Film;
import com.example.gestioncinema2.Classes.Personne;
import com.example.gestioncinema2.Classes.Seance;
import com.example.gestioncinema2.Controlleurs.FilmControlleur;
import com.example.gestioncinema2.Controlleurs.PersonneControlleur;
import com.example.gestioncinema2.Controlleurs.SalleControlleur;
import com.example.gestioncinema2.Controlleurs.SeanceControlleur;

import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.mail.*;

/**
 *
 * @author Lenovo
 */
public class Films extends javax.swing.JFrame {

    /**
     * Creates new form Films
     */
    public Films() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TitreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AnneeTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RealisateurTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DureeTxt = new javax.swing.JTextField();
        TarifTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescTxt = new javax.swing.JTextArea();
        ResBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Nos films disponibles");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Titre :");

        TitreTxt.setToolTipText("");
        TitreTxt.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Année :");

        AnneeTxt.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Realisateur :");

        RealisateurTxt.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Durée :");

        DureeTxt.setEnabled(false);

        TarifTxt.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tarif :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Description :");

        DescTxt.setColumns(20);
        DescTxt.setRows(5);
        DescTxt.setEnabled(false);
        jScrollPane2.setViewportView(DescTxt);

        ResBtn.setBackground(new java.awt.Color(255, 255, 204));
        ResBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ResBtn.setText("Reserver");
        ResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResBtnActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 204, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom film", "Duree", "Prix"
            }
        ) {
            final Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(ResBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RealisateurTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AnneeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TitreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(138, 138, 138)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TarifTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DureeTxt))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TitreTxt)
                        .addComponent(jLabel5)
                        .addComponent(DureeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AnneeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TarifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RealisateurTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addComponent(ResBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        FilmControlleur FC = new FilmControlleur();
        List<Film> Ls = null;
        String[] Columns ={"Titre","Duree","Prix"};
        String[][] Data = new String[100][100];
        try {
            Ls = FC.GetFilmsBySeance();

            int i =0;
            for (Film F:Ls) {
                Data[i][0]=F.getTitre();
                System.out.println(F.getDuree());
                Data[i][1]=String.valueOf(F.getDuree());
                Data[i][2]=F.getPrix()+"";
                i++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        DefaultTableModel DTM = new DefaultTableModel(Data,Columns);
        jTable1.setModel(DTM);
    }//GEN-LAST:event_formComponentShown

    public static void SendMail(String mail){
        final String username="oumaimamabrouki99";
        final String password="maimaaa3799";
        String from ="oumaimamabrouki99@gmail.com";
        String to = mail ;
        String host = "localhost";
        Properties properties = new Properties();
        properties.put("mail.smtp.host",host);
       // properties.put("mail.smtp.port","8080");
        properties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable","true");
        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username,password);
            }
        });
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));
            message.setSubject("Bienvenue dans notre Cinema");
            message.setText("Hello sir !");
            Transport.send(message);
            //System.out.println("yeees");
        }catch (Exception E ){
            System.out.println(E.getMessage());
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        String Titre =tbl.getValueAt(jTable1.getSelectedRow(),0).toString();
        String Prix =tbl.getValueAt(jTable1.getSelectedRow(),2).toString();
        String Duree =tbl.getValueAt(jTable1.getSelectedRow(),1).toString();
        String annee="";
        String Realisateur="";
        String Description="";
          FilmControlleur FC = new FilmControlleur();
          try {
              Film F = FC.RechercherFilm(Titre);
              if(F!=null){
                   annee =F.getAnneeRealisation();
                   Realisateur=F.getNomRealisateur();
                   Description= F.getDescription();
              }
          }catch (SQLException E){
              System.out.println(E.getMessage());
          }
          TitreTxt.setText(Titre);
          TarifTxt.setText(Prix);
          AnneeTxt.setText(annee);
          DescTxt.setText(Description);
          RealisateurTxt.setText(Realisateur);
          DureeTxt.setText(Duree);


    }//GEN-LAST:event_jTable1MouseClicked

    private void ResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResBtnActionPerformed
        SeanceControlleur SC = new SeanceControlleur();
        SalleControlleur SalleC = new SalleControlleur();
        PersonneControlleur PC = new PersonneControlleur();
         List<Seance> LS ;
         List<Seance> LS2 = new ArrayList<>();
         List<Personne> LP = new ArrayList<>();
        try {
            LS =SC.AllSeances();
            for (Seance seance: LS) {
                if(seance.getTitreFilm().equals(TitreTxt.getText())){
                    System.out.println(seance.getTitreFilm());
                    LS2.add(seance);
                }
            }
           for(int i=0;i<LS2.size();i++){
               //TODO: maybe this is wrong i'll check it later
               String CIN = JOptionPane.showInputDialog("Entrez votre CIN svp ");
               LP = PC.GetAllUsers();
               for (Personne p : LP) {
                     do{

                         if(p.getCIN().equals(CIN)){
                             if((SalleC.RechercherSalle(LS2.get(i).getIdSalle()).getNbrPlaces()>0)&&(SalleC.RechercherSalle(LS2.get(i).getIdSalle()).isStatut()==true)){
                                 String result = JOptionPane.showInputDialog("Combien de places vous allez reservez ?");
                                 if(SalleC.RechercherSalle(LS2.get(i).getIdSalle()).getNbrPlaces()>Integer.parseInt(result)){
                                     //TODO : mise a jour pour le nombre de salle dans la table salle
                                     int NbrPlace =   SalleC.RechercherSalle(LS2.get(i).getIdSalle()).getNbrPlaces()-Integer.parseInt(result);         //Nouveau nombre de places
                                     System.out.println("idPersonne"+p.getIdP());
                                     if( (PC.Reserver(p.getIdP(),LS2.get(i).getNumSeance())))
                                     {
                                         if( SalleC.updateSalle(SalleC.RechercherSalle(LS2.get(i).getIdSalle()).getNumeroSalle(),NbrPlace)){
                                             JOptionPane.showMessageDialog(null,"Reservation est terminée avec success","Confirmation",1);
                                             try {
                                                 System.out.println(p.getMail());
                                                 SendMail(p.getMail());
                                                 Thread.sleep(2000);
                                                 JOptionPane.showMessageDialog(null,"Mail envoyé");
                                             } catch (InterruptedException e) {
                                                 e.printStackTrace();
                                             }
                                         }
                                     }
                                 }
                                 break;
                             }
                         }
                     }while (!p.getCIN().equals(CIN));
               }
           }
            JFrame f ;
            JTable j;
            f = new JFrame();
            f.setTitle("Seances Disponibles");
            String[] columns={"Nom Film, DateHeure,Salle"};
            String[][] data = new String[10][10];
            int i=0;
            for (Seance T:LS2) {
                System.out.println("T:"+T.getTitreFilm());
                data[i][0]=T.getTitre();
                data[i][1]=T.getDateHeure();
                data[i][2]=""+T.getIdSalle();
                data[i][4]="TEST BUTTON";
                i++;
            }
            j = new JTable(data,columns);
            j.setBounds(30,40,200,300);
            JScrollPane sp = new JScrollPane(j);
            f.add(sp);
            f.setSize(500,200);
            f.setVisible(true);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ResBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Films.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Films().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnneeTxt;
    private javax.swing.JTextArea DescTxt;
    private javax.swing.JTextField DureeTxt;
    private javax.swing.JTextField RealisateurTxt;
    private javax.swing.JButton ResBtn;
    private javax.swing.JTextField TarifTxt;
    private javax.swing.JTextField TitreTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
